name: gm-cli

on:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        
      - name: 📄 Run gm-cli
        # Use npx to execute the locally installed package, passing your config file
        run: gm-cli compile
        
      - name: Report Successful GameMaker Build Client Execution
        run: |
          echo "###################################################"
          echo "## GM-CLI WORKFLOW EXECUTED SUCCESSFULLY! ##"
          echo "###################################################"

          