name: GM CLI Run

on:
  push:
    branches:
      - 'feature/**'

jobs:
  run-gm-cli:
    runs-on: ubuntu-latest
    container:
      image: monkeyknuckles/gm-cli:latest
      # Set the environment variable for the entire container
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GameMaker CLI for Project A
        working-directory: ./palette-controller
        run: gm-cli run