# LINT MARKDOWN FILES WITH MARKDOWNLINT-CLI2 LINTER

name: Markdown Lint

# Performs actions on successful pull or push 

on: [push, pull_request]
  
# Sets Distribution To Use And Initializes Linting Job

jobs:
  lint:
    runs-on: ubuntu-latest
    
    container:
      image: monkeyknuckles/markdownlint-cli2

    # Steps Required In Order To Lint Markdown Files

    steps:

    # Checkout Code

      - name: Checkout code
        uses: actions/checkout@v3

    # Copy Configuration File Containing Markdown Linting Rules From The Container To The Workspace

      - name: Copy markdownlint config
        run: cp /app/.markdownlint.yaml $GITHUB_WORKSPACE

    # Lint All Markdownfiles With Extension '*.Md' Located Anywhere In The Project Folder
        
      - name: Run markdownlint-cli2
        run: markdownlint-cli2 "**/*.md" "#node_modules"
