name: CommitLint Check

# PERFORMS ACTIONS ON SUCCESSFUL PULL OR PUSH
on: [push, pull_request]

# SETS DISTRIBUTION TO USE AND INITIALIZES COMMITLINT JOB
jobs:
  lint:
    runs-on: ubuntu-latest
    
    # USES MONKEYKNUCKLES/COMMITLINT DOCKER IMAGE AS THE CONTAINER
    container:
      image: monkeyknuckles/commitlint

    # STEPS REQUIRED IN ORDER TO LINT COMMIT MESSAGES
    steps:

      # CHECKOUT CODE
      - name: Checkout code
        uses: actions/checkout@v3

      # RUN COMMITLINT TO LINT THE COMMIT MESSAGES IN THE REPOSITORY, IGNORING LOCKS
      - name: Run commitlint
        run: |
          GIT_OPTIONAL_LOCKS=0 commitlint --config /app/commitlint.config.js --from HEAD~1 --to HEAD
