# LINT MARKDOWN FILES WITH MARKDOWNLINT-CLI2 LINTER

name: Commit Lint

# PERFORMS ACTIONS ON SUCCESSFUL PULL OR PUSH

on: [push, pull_request]

# SETS DISTRIBUTION TO USE AND INITIALIZES LINTING JOB

jobs:
  lint:
    runs-on: ubuntu-latest
    
    container:
      image: monkeyknuckles/commitlint

    # STEPS REQUIRED IN ORDER TO LINT MARKDOWN FILES

    steps:

    # CHECKOUT CODE

      - name: Checkout code
        uses: actions/checkout@v3

      - name: lsa
        run: ls -a

    # COPY CONFIGURATION FILE CONTAINING MARKDOWN LINTING RULES FROM THE CONTAINER TO THE WORKSPACE

      - name: Copy commitlint config
        run: cp /app/commitlint.config.js $GITHUB_WORKSPACE

      - name: Set Git safe directory
        run: git config --global --add safe.directory /__w/sandbox/sandbox

    # LINT ALL MARKDOWNFILES WITH EXTENSION '*.MD' LOCATED ANYWHERE IN THE PROJECT FOLDER
        
      - name: Run commitlint
        run: commitlint --config commitlint.config.js --from=HEAD~1 --to=HEAD






