name: Production Deployment

on:
  workflow_call:
    # Receives the call from CI Controller

jobs:
  # 1. Linting Jobs (Running in parallel)
  commit-lint:
    uses: ./.github/workflows/commitlint.yaml
    secrets: inherit

  markdown-lint:
    uses: ./.github/workflows/markdownlint.yaml
    secrets: inherit

  publish-development-release:
    needs: [commit-lint, markdown-lint]
    uses: ./.github/workflows/semantic-release.yaml
    with:
      environment: production
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      SSH_SIGNING_KEY: ${{ secrets.SSH_SIGNING_KEY }}